# Generated by Django 2.0b1 on 2017-10-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='概要')),
                ('cover', models.ImageField(upload_to='', verbose_name='封面')),
                ('content', models.TextField(verbose_name='正文')),
                ('promote', models.BooleanField(verbose_name='置于首页')),
                ('weight', models.IntegerField(verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='分类')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='访客姓名')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('articleOfInterest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Article', verbose_name='感兴趣的文章')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='core.Tag', verbose_name='标签'),
        ),
    ]
